export const WORD_LIST = [
  "Stapler",
  "Desk",
  "Pay cheque",
  "Fax machine",
  "Phone",
  "Paper",
  "Light",
  "Chair",
  "Desk lamp",
  "Notepad",
  "Paper clips",
  "Binder",
  "Calculator",
  "Calendar",
  "Sticky Notes",
  "Pens",
  "Pencils",
  "Notebook",
  "Book",
  "Chairs",
  "Chairs",
  "Coffee mug",
  "Thermos",
  "Hot cup",
  "Glue",
  "Clipboard",
  "Paperclips",
  "Chocolate",
  "Secretary",
  "Work",
  "Paperwork",
  "Workload",
  "Employee",
  "Boredom",
  "Coffee",
  "Golf",
  "Laptop",
  "Sandcastle",
  "Monday",
  "Vanilla",
  "Bamboo",
  "Sneeze",
  "Scratch",
  "Celery",
  "Hammer",
  "Frog",
  "Tennis",
  "Hot dog",
  "Pants",
  "Bridge",
  "Bubblegum",
  "Candy bar",
  "Bucket",
  "Skiing",
  "Sledding",
  "Snowboarding",
  "Snowman",
  "Polar bear",
  "Cream",
  "Waffle",
  "Pancakes",
  "Ice cream",
  "Sundae",
  "beach",
  "Sunglasses",
  "Surfboard",
  "Watermelon",
  "Baseball",
  "Bat",
  "Ball",
  "T-shirt",
  "Kiss",
  "Jellyfish",
  "Jelly",
  "Butterfly",
  "Spider",
  "Broom",
  "Spiderweb",
  "Mummy",
  "Candy",
  "Bays",
  "Squirrels",
  "Basketball",
  "Water Bottle",
  "Unicorn",
  "Dog leash",
  "Newspaper",
  "Hammock",
  "Video camera",
  "Money",
  "Smiley face",
  "Umbrella",
  "Picnic basket",
  "Teddy bear",
  "Ambulance",
  "Pyramids",
  "Bacteria",
  "Goosebumps",
  "Pizza",
  "Platypus",
  "Clam Chowder",
  "Goldfish bowl",
  "Skull",
  "Spiderweb",
  "Smoke",
  "Tree",
  "Ice",
  "Blanket",
  "Seaweed",
  "Flame",
  "Bubble",
  "Hair",
  "Tooth",
  "Leaf",
  "Worm",
  "Sky",
  "Apple",
  "Plane",
  "Cow",
  "House",
  "Dog",
  "Car",
  "Bed",
  "Furniture",
  "Train",
  "Rainbow",
  "Paintings",
  "Drawing",
  "Cup",
  "Plate",
  "Bowl",
  "Cushion",
  "Sofa",
  "Sheet",
  "Kitchen",
  "Table",
  "Candle",
  "Shirt",
  "Clothes",
  "Dress",
  "Pillow",
  "Home",
  "Toothpaste",
  "Guitar",
  "Schoolbag",
  "Pencil Case",
  "Glasses",
  "Towel",
  "Watch",
  "Piano",
  "Pen",
  "Hat",
  "Shoes",
  "Socks",
  "Jeans",
  "Hair Gel",
  "Keyboard",
  "Bra",
  "Jacket",
  "Tie",
  "Bandage",
  "Scarf",
  "Hair Brush",
  "Cell Phone",
  "Printer",
  "Cork Board",
  "Office Supplies",
  "Cork Board",
  "Paperweight",
  "Letter Opener",
  "Post-It notes",
  "Pen holder",
  "File cabinet",
  "Boss",
  "Water-cooler",
  "Commute",
  "Lunch break",
  "Employer",
  "Late",
  "Passion",
  "Ambition",
  "Pay",
  "Pride",
  "Unemployment",
  "Job",
  "Hire",
  "Lazy",
  "Worried",
  "Tired",
  "Poverty",
  "Olympics",
  "Recycle",
  "Black hole",
  "Applause",
  "Blizzard",
  "Sunburn",
  "Time Machine",
  "Atlantis",
  "Swamp",
  "Sunscreen",
  "Dictionary",
  "Century",
  "Sculpture",
  "Sneaker",
  "Admiral",
  "Water polo",
  "Ninja",
  "Snorkeling",
  "Surfing",
  "Volleyball",
  "Pitcher",
  "Catcher",
  "Batter",
  "Home Plate",
  "Swing",
  "Cheerleader",
  "Pumpkin",
  "Halloween",
  "Ghost",
  "Spooky",
  "Skeleton",
  "Vampire",
  "Scary",
  "Witch",
  "Noodles",
  "Hula hoop",
  "Unicycle",
  "Whiteboard",
  "Knitting",
  "Thunderstorm",
  "Bubble wrap",
  "Thermometer",
  "Skipping Rope",
  "Canned Food",
  "Waffles",
  "Chalkboard",
  "Home run",
  "Milkshake",
  "Snowball fight",
  "Bug zapper",
  "Pot of gold",
  "Loudspeaker",
  "Wind chimes",
  "Musical instrument",
  "Bird feeder",
  "Bookworm",
  "Wig",
  "Monster Truck",
  "Houseplant",
  "Pie chart",
  "Water gun",
  "Shopping cart",
  "Knife and fork",
  "Blue whale",
  "Canary Islands",
  "Christmas tree",
  "Daytime",
  "Earthquake",
  "Frog legs",
  "Junkyard",
  "Vomiting",
  "Aardvark",
  "Dolphin",
  "Rainforest",
  "Spiders Web",
  "Great Wall of China",
  "Bat",
  "Worms",
  "X-Ray",
  "Yawning",
  "Daytime TV",
  "Fireman",
  "Frogs Legs",
  "Hard hat",
  "Hospital gown",
  "Invisible Man",
  "Underwear",
  "Quicksand",
  "Stomach ache",
  "Vacuum cleaner",
  "Swiss cheese",
  "Cream cheese",
  "Pizza crust",
  "Bruise",
  "Fog",
  "Crust",
  "Battery",
  "Cereal",
  "Blood",
  "Moss",
  "Thorn",
  "Algae",
  "Slug",
  "Antenna",
  "Butterfly Wing",
  "Parasite",
  "Pollen",
  "Asteroid",
  "Family",
  "Painting",
  "Sketch",
  "Wallpaper",
  "Chandelier",
  "Ketchup",
  "Plane ticket",
  "Fruit juice",
  "Slippers",
  "Sneakers",
  "Salary",
  "Punctuality",
  "Slacking",
  "Stress",
  "Overtime",
  "Redundant",
  "Unemployed",
  "Disconnect",
  "Freelance",
  "Part-time",
  "Workaholic",
  "Stressful",
  "Exhausted",
  "Worries",
  "Career",
  "Overqualified",
  "Unhappy",
  "Panama Canal",
  "Cheer",
  "Vacation",
  "Trick-or-treat",
  "Minimalism",
  "Egghead",
  "Hypnosis",
  "Fidget spinner",
  "Artificial Intelligence",
  "Scientific research",
  "Dreamcatcher",
  "Screaming child",
  "Jello shots",
  "Surprise party",
  "Chilli cheese dog",
  "Mugshot",
  "Moonwalk",
  "Couch potato",
  "Aurora Borealis",
  "Leaning Tower of Pisa",
  "Fairy",
  "Steamed Hams",
  "Hornets Nest",
  "Immune System",
  "Mushroom",
  "The Sun",
  "Zebra",
  "Computer",
  "Lawnmower",
  "Moonwalking",
  "Oyster crackers",
  "Striped pajamas",
  "Shaving cream",
  "Hiccups",
  "Breath Mints",
  "Giant zit",
  "Snot bubbles",
  "Body odor",
  "Chicken pox",
  "Crustacean",
];
