import { GameStateProvider } from "@/components/game/game-state-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="HandheldFriendly" content="true" />
      </head>
      <body className={inter.className}>
        <GameStateProvider>{children}</GameStateProvider>
      </body>
    </html>
  );
}
