import { GameStateProvider } from "@/components/game/game-state-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <meta name="HandheldFriendly" content="true" />
        </head>
        <body className={GeistSans.className}>
          <GameStateProvider>{children}</GameStateProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
